### ISSUE TITLE
Store USP block duplicating after resizing window

### ISSUE THREAD

**Issue by gjportegies** [studioemma/magento2-theme-optimus#19]
The .store-usp is duplicating after resizing the window multiple times.

<img width="1297" alt="schermafbeelding 2018-12-29 om 12 11 55" src="https://user-images.githubusercontent.com/6707410/50537669-f8c6f600-0b62-11e9-86a4-ac2c1b8f5479.png">

This is probably caused in the responsive-optimus.js by prepending the .store-usp block when switching to mobile and desktop.

**Comment by Quinten** [comment]
The problem is that there is a widget added on the demo site to the footer. This widget probably comes from the Magento 2 sample data. Because the html code of the widget also contains the class `footer` the usp's get duplicated when they are moved. A temporary fix is to have only one div with class `footer`. So  i will remove the class in the widget. You probably took this screenshot on the demosite? The widget isn't supposed to be there on a real site.
